// Loosened from a narrow union to a plain string: this list covers the world's major
// languages (100+), which is only practical to type-check as a free-form code.
export type AltTextLanguage = string;

export const LANGUAGE_OPTIONS: { value: AltTextLanguage; label: string }[] = [
  { value: "en", label: "English" },
  { value: "es", label: "Spanish" },
  { value: "fr", label: "French" },
  { value: "de", label: "German" },
  { value: "it", label: "Italian" },
  { value: "pt", label: "Portuguese" },
  { value: "nl", label: "Dutch" },
  { value: "sv", label: "Swedish" },
  { value: "no", label: "Norwegian" },
  { value: "da", label: "Danish" },
  { value: "fi", label: "Finnish" },
  { value: "is", label: "Icelandic" },
  { value: "pl", label: "Polish" },
  { value: "cs", label: "Czech" },
  { value: "sk", label: "Slovak" },
  { value: "hu", label: "Hungarian" },
  { value: "ro", label: "Romanian" },
  { value: "bg", label: "Bulgarian" },
  { value: "el", label: "Greek" },
  { value: "hr", label: "Croatian" },
  { value: "sr", label: "Serbian" },
  { value: "sl", label: "Slovenian" },
  { value: "uk", label: "Ukrainian" },
  { value: "ru", label: "Russian" },
  { value: "be", label: "Belarusian" },
  { value: "lt", label: "Lithuanian" },
  { value: "lv", label: "Latvian" },
  { value: "et", label: "Estonian" },
  { value: "tr", label: "Turkish" },
  { value: "ar", label: "Arabic" },
  { value: "he", label: "Hebrew" },
  { value: "fa", label: "Persian" },
  { value: "ur", label: "Urdu" },
  { value: "hi", label: "Hindi" },
  { value: "bn", label: "Bengali" },
  { value: "pa", label: "Punjabi" },
  { value: "gu", label: "Gujarati" },
  { value: "mr", label: "Marathi" },
  { value: "ta", label: "Tamil" },
  { value: "te", label: "Telugu" },
  { value: "kn", label: "Kannada" },
  { value: "ml", label: "Malayalam" },
  { value: "si", label: "Sinhala" },
  { value: "ne", label: "Nepali" },
  { value: "th", label: "Thai" },
  { value: "vi", label: "Vietnamese" },
  { value: "id", label: "Indonesian" },
  { value: "ms", label: "Malay" },
  { value: "tl", label: "Filipino (Tagalog)" },
  { value: "km", label: "Khmer" },
  { value: "lo", label: "Lao" },
  { value: "my", label: "Burmese" },
  { value: "zh", label: "Chinese (Simplified)" },
  { value: "zh-TW", label: "Chinese (Traditional)" },
  { value: "ja", label: "Japanese" },
  { value: "ko", label: "Korean" },
  { value: "mn", label: "Mongolian" },
  { value: "kk", label: "Kazakh" },
  { value: "uz", label: "Uzbek" },
  { value: "az", label: "Azerbaijani" },
  { value: "ka", label: "Georgian" },
  { value: "hy", label: "Armenian" },
  { value: "sw", label: "Swahili" },
  { value: "am", label: "Amharic" },
  { value: "ha", label: "Hausa" },
  { value: "yo", label: "Yoruba" },
  { value: "ig", label: "Igbo" },
  { value: "zu", label: "Zulu" },
  { value: "xh", label: "Xhosa" },
  { value: "af", label: "Afrikaans" },
  { value: "so", label: "Somali" },
  { value: "sq", label: "Albanian" },
  { value: "mk", label: "Macedonian" },
  { value: "bs", label: "Bosnian" },
  { value: "mt", label: "Maltese" },
  { value: "cy", label: "Welsh" },
  { value: "ga", label: "Irish" },
  { value: "gd", label: "Scottish Gaelic" },
  { value: "eu", label: "Basque" },
  { value: "ca", label: "Catalan" },
  { value: "gl", label: "Galician" },
];
